backend:
  name: github
  repo: liorchamla/gatsby-netlify-cms

media_folder: static/assets

collections:
  - name: blog
    label: Blog
    folder: markdown/blog
    create: true
    fields:
      - { name: path, label: Path }
      - { name: date, label: Date, widget: date }
      - { name: title, label: Title }
      - { name: sections, label: Sections, widget: list, fields: [{label: Heading, name: heading, widget: string}, {label: "Background image", name: background, widget: file}, {label: Content, name: content, widget: markdown}]}